version = 1

[[analyzers]]
name = "kotlin"

  [analyzers.meta]
  runtime_version = "1.8"
  language_version = "1.7"

[[analyzers]]
name = "swift"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "ruby"