name: v2_1
description: "Comfy Space 2.1"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.4+8

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  rename: ^3.0.2
  firebase_core: ^3.0.0
  gap: ^3.0.1
  firebase_auth: ^5.0.0
  google_sign_in: ^6.2.1
  dotted_border: ^2.1.0
  cloud_firestore: ^5.0.0
  reorderable_grid: ^1.0.10
  rive: ^0.13.1
  unsplash_client: ^2.2.0
  typewritertext: ^3.0.2
  flutter_floating_bottom_bar: ^1.2.0
  dot_navigation_bar: ^1.0.2
  salomon_bottom_bar: ^3.3.2
  flutter_expandable_fab: ^2.0.0
  dartssh2: ^2.8.2
  shared_preferences: ^2.2.2
  flutter_spinkit: ^5.2.1
  iconsax: ^0.0.8
  animated_introduction: ^1.0.4
  flutter_onboarding_slider: ^1.0.11
  flutter_animate: ^4.5.0
  carousel_slider: ^4.2.1
  card_swiper: ^3.0.1
  animated_text_kit: ^4.2.2
  flutter_launcher_icons: ^0.13.1
  icons_launcher: ^2.1.7
  flutter_slidable: ^3.1.0
  firebase_storage: ^12.0.0
  flutter_markdown: ^0.7.1
  like_button: ^2.0.5
  markdown_widget: ^2.3.2+6
  dart_markdown: ^3.1.7
  flutter_widget_from_html_core: ^0.15.1
  mailer: ^6.1.0
  icons_plus: ^5.0.0
  material_design_icons_flutter: ^7.0.7296
  sign_in_with_apple: ^6.1.0
  web_socket_channel: ^3.0.0
  url_launcher: ^6.2.6
  flutter_animated_button: ^2.0.3
  flutter_chat_ui: ^1.6.13
  uuid: ^4.4.0
  flutter_animated_icons: ^1.0.1
  item_picker: ^2.0.0
  bubble: ^1.2.1
  introduction_screen: ^3.1.14
  webview_flutter: ^4.8.0

  flutter_chat_types: any
  http: ^1.2.1
  slidable_button: ^3.0.0+1
  gradient_slide_to_act: ^0.0.2
  slider_button: ^2.1.0
  rename_app: ^1.5.0
  flutter_tts: ^4.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/image_asset/
    - assets/spinning-jax.gif
    - assets/tutorials/
    - assets/raspberrypi_4.png
    - assets/comfy_logo_ambience.png
    - assets/comfy_icon.png
    - assets/comfy_logo_ios.png
    - assets/google_icon.png
    - assets/apple_icon.png
    - assets/comfy_logo_no_background.png
    - assets/4_enemies_sprite_sheet/SLIME/
    - assets/YoMoji!/
    - assets/flutter-webp-nomeno/characters/
    - assets/flutter-webp-nomeno/characters/generated/
    - assets/froggie/
    - assets/pattern/
    - assets/rive/arrow.riv
    - assets/component_assets/floating_button/
    - assets/notion_style/
    - assets/comfy_logo_android.png
    - shorebird.yaml


icons_launcher:
  image_path: "assets/comfy_logo_ambience.png"
  platforms:
    android:
      enable: true
      image_path: "assets/comfy_icon.png"
    web:
      enable: true
      image_path: "assets/comfy_logo_ambience.png"
      favicon_path: "assets/comfy_logo_ambience.png"
    macos:
      enable: true
      image_path: "assets/comfy_logo_ambience.png"
    windows:
      enable: true
      image_path: "assets/comfy_logo_ambience.png"
    linux:
      enable: true
      image_path: "assets/comfy_logo_ambience.png"

flutter_launcher_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/comfy_logo_ios.png"
  min_sdk_android: 21 # android min sdk min:16, default 21